name: Build OpenWrt

on:
workflow_dispatch: # elle “Run workflow” tuşuyla başlat
push:
branches: [ main ]

jobs:
build:
runs-on: ubuntu-22.04 # 2‑core / 14 GB RAM / 70 GB disk

steps:
- name: Checkout source
uses: actions/checkout@v4

- name: Set up build deps
run: |
sudo apt-get update
sudo apt-get install -y build-essential clang flex bison g++
gawk gcc-multilib g++-multilib gettext git libncurses-dev
libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

- name: Restore DL cache
uses: actions/cache@v4
with:
path: dl
key: ${{ runner.os }}-openwrt-dl-${{ hashFiles('.config') }}
restore-keys: |
${{ runner.os }}-openwrt-dl-

- name: Configure
run: make defconfig

- name: Build
run: make -j$(nproc) V=s

- name: Upload firmware images
uses: actions/upload-artifact@v4
with:
name: openwrt-images
path: bin/targets/**/*.bin
